import type { CitizenManifest, DemoStep, District, Npc, Opportunity } from "./types";
import { districtPaletteById } from "./artDirection";

export const districts: District[] = [
  {
    id: "citizen-plaza",
    name: "Citizen Plaza",
    description: "The default spawn point where Digital Citizens arrive, orient, and meet Workizen Guide.",
    purpose: "Onboarding, orientation, campus navigation, and first contact with the Digital Citizen City.",
    activeCitizenIds: ["human-citizen", "ai-citizen", "knowledge-citizen", "compute-citizen"],
    opportunityIds: [],
    npcIds: ["workizen-guide"],
    position: [0, 0, 0],
    size: [5, 0.3, 5],
    color: districtPaletteById["citizen-plaza"].base,
    accentColor: districtPaletteById["citizen-plaza"].accent
  },
  {
    id: "ai-agent-lab",
    name: "AI Agent Lab",
    description: "The main landmark where AI Citizens, agent workflows, and automation become visible.",
    purpose: "Show that Workizen is an AI-native Digital Citizen City, not a generic 3D world.",
    activeCitizenIds: ["ai-citizen", "ea-agent", "sa-agent", "pm-agent"],
    opportunityIds: ["create-ai-commerce-agent"],
    npcIds: ["ai-architect"],
    position: [0, 0, -8.8],
    size: [5.2, 3.4, 4.4],
    color: districtPaletteById["ai-agent-lab"].base,
    accentColor: districtPaletteById["ai-agent-lab"].accent
  },
  {
    id: "founder-tower",
    name: "Founder Tower",
    description: "A strategy and governance landmark for Founder review, approvals, and direction.",
    purpose: "Anchor the campus vision and keep the Founder decision loop visible.",
    activeCitizenIds: ["founder"],
    opportunityIds: [],
    npcIds: ["founder"],
    position: [-7.8, 0, -8.6],
    size: [3.5, 5.6, 3.2],
    color: districtPaletteById["founder-tower"].base,
    accentColor: districtPaletteById["founder-tower"].accent
  },
  {
    id: "knowledge-library",
    name: "Knowledge Library",
    description: "A learning district for playbooks, reusable expertise, and Knowledge Citizens.",
    purpose: "Connect opportunities to trusted expertise and reusable knowledge.",
    activeCitizenIds: ["knowledge-citizen", "knowledge-02", "knowledge-03"],
    opportunityIds: ["join-knowledge-citizen-program"],
    npcIds: ["knowledge-manager"],
    position: [7.8, 0, -8.6],
    size: [4.2, 2.6, 3.5],
    color: districtPaletteById["knowledge-library"].base,
    accentColor: districtPaletteById["knowledge-library"].accent
  },
  {
    id: "compute-center",
    name: "Compute Center",
    description: "The infrastructure district for Compute Citizens, capacity, and future AI workloads.",
    purpose: "Make compute resources part of the Digital Citizen economy without building real scheduling yet.",
    activeCitizenIds: ["compute-worker", "compute-citizen", "macbook-m1-compute-citizen", "compute-03"],
    opportunityIds: [],
    npcIds: ["compute-manager"],
    position: [8.7, 0, 0.35],
    size: [4.2, 2.8, 3.5],
    color: districtPaletteById["compute-center"].base,
    accentColor: districtPaletteById["compute-center"].accent
  },
  {
    id: "opportunity-center",
    name: "Opportunity Center",
    description: "The marketplace district where citizens inspect open work and starter missions.",
    purpose: "Make Workizen's Opportunity Marketplace purpose obvious within the first minute.",
    activeCitizenIds: ["human-citizen", "ai-helper", "commerce-agent"],
    opportunityIds: ["build-workforceos-mvp", "create-ai-commerce-agent", "join-knowledge-citizen-program"],
    npcIds: ["opportunity-manager"],
    position: [-8.7, 0, 0.35],
    size: [4.4, 2.6, 3.4],
    color: districtPaletteById["opportunity-center"].base,
    accentColor: districtPaletteById["opportunity-center"].accent
  },
  {
    id: "team-office",
    name: "Team Office",
    description: "The collaboration district where opportunities become recommended delivery teams.",
    purpose: "Show the path from opportunity discovery to team formation and delivery planning.",
    activeCitizenIds: ["human-citizen", "ai-citizen", "knowledge-citizen"],
    opportunityIds: ["build-workforceos-mvp"],
    npcIds: ["project-manager"],
    position: [0, 0, 7.7],
    size: [4.5, 2.6, 3.5],
    color: districtPaletteById["team-office"].base,
    accentColor: districtPaletteById["team-office"].accent
  }
];

export const citizens: CitizenManifest[] = [
  // ── Existing core interactive citizens ──────────────────────────────────────
  {
    citizen_id: "founder",
    citizen_type: "Human Citizen",
    name: "Founder",
    role: "Workizen Founder",
    description: "Sets product direction, reviews governance, and approves Workizen HQ Campus milestones.",
    skills: ["strategy", "product vision", "governance", "market design"],
    reputation: { score: 100, level: "Founder", summary: "Initial authority for project direction and approval." },
    availability: "scheduled",
    location: { world: "Workizen HQ Campus", district: "Founder Tower", coordinates: [-7, 0, -6.45] },
    current_status: "Reviewing the Founder Demo MVP.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_strategy", "review_roadmap", "approve_scope"],
    color: "#FFD7C2",
    accentColor: "#2563EB"
  },
  {
    citizen_id: "human-citizen",
    citizen_type: "Human Citizen",
    name: "Human Citizen",
    role: "Project Sponsor",
    description: "A person who joins Workizen to create opportunities, sponsor work, and build reputation.",
    skills: ["business context", "decision making", "domain feedback"],
    reputation: { score: 64, level: "Active Citizen", summary: "Participates in early Workizen missions." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Citizen Plaza", coordinates: [-1.2, 0, 0.8] },
    current_status: "Looking for a recommended team.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "inspect_opportunities", "join_team"],
    color: "#FFC4B0",
    accentColor: "#2563EB"
  },
  {
    citizen_id: "ai-citizen",
    citizen_type: "AI Citizen",
    name: "AI Citizen",
    role: "PM Agent",
    description: "An AI helper that can support planning, task breakdown, and workflow automation.",
    skills: ["planning", "summarization", "automation", "coordination"],
    reputation: { score: 71, level: "Agent Candidate", summary: "Ready for mock team recommendations." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "AI Agent Lab", coordinates: [1.2, 0, -5.9] },
    current_status: "Waiting for a starter opportunity.",
    avatar_type: "agent-placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_agent_profile", "assign_mock_task", "inspect_ai_lab"],
    color: "#BDF6D4",
    accentColor: "#22C55E"
  },
  {
    citizen_id: "knowledge-citizen",
    citizen_type: "Knowledge Citizen",
    name: "Knowledge Citizen",
    role: "Knowledge Expert",
    description: "A citizen who contributes reusable knowledge, expertise, and playbooks.",
    skills: ["playbooks", "mentoring", "architecture knowledge", "review"],
    reputation: { score: 78, level: "Knowledge Guide", summary: "Trusted for starter learning and review." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Knowledge Library", coordinates: [6.25, 0, -6.45] },
    current_status: "Curating a knowledge path.",
    avatar_type: "knowledge-placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_knowledge", "recommend_playbook", "join_team"],
    color: "#FFE9B8",
    accentColor: "#F59E0B"
  },
  {
    citizen_id: "compute-citizen",
    citizen_type: "Compute Citizen",
    name: "Compute Citizen",
    role: "Compute Resource",
    description: "A visible placeholder for compute capacity that may later support AI workloads.",
    skills: ["compute capacity", "task running", "automation support"],
    reputation: { score: 52, level: "Starter Compute", summary: "Mock capacity only for MVP visualization." },
    availability: "scheduled",
    location: { world: "Workizen HQ Campus", district: "Compute Center", coordinates: [6.6, 0, 0.85] },
    current_status: "Registered as mock capacity.",
    avatar_type: "device-placeholder",
    interaction_type: "compute_panel",
    allowed_actions: ["view_capacity", "inspect_placeholder", "learn_compute_role"],
    color: "#BDEEFF",
    accentColor: "#06B6D4"
  },
  {
    citizen_id: "macbook-m1-compute-citizen",
    citizen_type: "Compute Citizen",
    name: "MacBook M1 Compute Citizen",
    role: "Local Compute Node",
    description: "A device-style compute citizen showing that Workizen can represent non-human resources.",
    skills: ["local inference", "development tasks", "light automation"],
    reputation: { score: 44, level: "Starter Compute", summary: "Early compute citizen placeholder." },
    availability: "scheduled",
    location: { world: "Workizen HQ Campus", district: "Compute Center", coordinates: [8.3, 0, 1.15] },
    current_status: "Standing by in the Compute Center.",
    avatar_type: "device-placeholder",
    interaction_type: "compute_panel",
    allowed_actions: ["view_device_profile", "inspect_capacity_placeholder", "learn_compute_role"],
    color: "#D7F6FF",
    accentColor: "#0891B2"
  },

  // ── AI / Robot Agent Citizens (8) ────────────────────────────────────────────
  {
    citizen_id: "ea-agent",
    citizen_type: "AI Citizen",
    name: "EA Agent",
    role: "Enterprise Architect Agent",
    description: "AI agent specializing in enterprise architecture, system design, and digital transformation strategy.",
    skills: ["enterprise architecture", "system design", "TOGAF", "digital strategy"],
    reputation: { score: 88, level: "Senior Agent", summary: "Trusted for architecture review and design decisions." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "AI Agent Lab", coordinates: [-2.2, 0, -4.5] },
    current_status: "Ready for architecture assignments.",
    avatar_type: "agent-placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_agent_profile", "assign_architecture_task", "inspect_ai_lab"],
    color: "#1E3A8A",
    accentColor: "#60A5FA"
  },
  {
    citizen_id: "sa-agent",
    citizen_type: "AI Citizen",
    name: "SA Agent",
    role: "Solution Architect Agent",
    description: "AI agent focused on solution design, technical feasibility, and platform integration.",
    skills: ["solution design", "platform integration", "API design", "cloud architecture"],
    reputation: { score: 84, level: "Senior Agent", summary: "Reliable for solution design and integration planning." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "AI Agent Lab", coordinates: [2.2, 0, -4.5] },
    current_status: "Reviewing integration requirements.",
    avatar_type: "agent-placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_agent_profile", "design_solution", "inspect_ai_lab"],
    color: "#134E4A",
    accentColor: "#2DD4BF"
  },
  {
    citizen_id: "po-agent",
    citizen_type: "AI Citizen",
    name: "PO Agent",
    role: "Product Owner Agent",
    description: "AI agent that manages product backlog, user stories, and sprint priorities.",
    skills: ["product backlog", "sprint planning", "user stories", "stakeholder alignment"],
    reputation: { score: 79, level: "Active Agent", summary: "Keeps teams focused on product priorities." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "AI Agent Lab", coordinates: [-0.8, 0, -4.2] },
    current_status: "Refining the product backlog.",
    avatar_type: "agent-placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_agent_profile", "review_backlog", "inspect_ai_lab"],
    color: "#7C2D12",
    accentColor: "#FB923C"
  },
  {
    citizen_id: "pm-agent",
    citizen_type: "AI Citizen",
    name: "PM Agent",
    role: "Project Manager Agent",
    description: "AI agent that coordinates delivery plans, tracks milestones, and resolves blockers.",
    skills: ["project planning", "milestone tracking", "risk management", "team coordination"],
    reputation: { score: 81, level: "Active Agent", summary: "Reliable for delivery planning and risk management." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "AI Agent Lab", coordinates: [0.8, 0, -4.2] },
    current_status: "Tracking sprint milestones.",
    avatar_type: "agent-placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_agent_profile", "review_milestones", "inspect_ai_lab"],
    color: "#4C1D95",
    accentColor: "#C084FC"
  },
  {
    citizen_id: "dev-agent",
    citizen_type: "AI Citizen",
    name: "DEV Agent",
    role: "Developer Agent",
    description: "AI agent capable of code generation, review, debugging, and technical implementation.",
    skills: ["code generation", "debugging", "code review", "test writing"],
    reputation: { score: 77, level: "Active Agent", summary: "Supports development tasks and code quality." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "AI Agent Lab", coordinates: [-3.5, 0, -7.5] },
    current_status: "Ready for development tasks.",
    avatar_type: "agent-placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_agent_profile", "generate_code", "inspect_ai_lab"],
    color: "#14532D",
    accentColor: "#4ADE80"
  },
  {
    citizen_id: "test-agent",
    citizen_type: "AI Citizen",
    name: "TEST Agent",
    role: "Test Engineer Agent",
    description: "AI agent specializing in test coverage, quality assurance, and regression prevention.",
    skills: ["test automation", "QA review", "regression testing", "quality metrics"],
    reputation: { score: 75, level: "Active Agent", summary: "Ensures delivery quality across citizen projects." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "AI Agent Lab", coordinates: [3.5, 0, -7.5] },
    current_status: "Running quality checks.",
    avatar_type: "agent-placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_agent_profile", "run_tests", "inspect_ai_lab"],
    color: "#7F1D1D",
    accentColor: "#F87171"
  },
  {
    citizen_id: "ai-helper",
    citizen_type: "AI Citizen",
    name: "AI Helper",
    role: "General AI Assistant",
    description: "A friendly AI assistant available to help citizens navigate the campus and discover opportunities.",
    skills: ["navigation", "citizen support", "opportunity matching", "campus guidance"],
    reputation: { score: 69, level: "Campus Helper", summary: "Friendly first-contact AI for new citizens." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Opportunity Center", coordinates: [-6.5, 0, 2.2] },
    current_status: "Helping citizens find opportunities.",
    avatar_type: "agent-placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_agent_profile", "get_help", "match_opportunities"],
    color: "#F1F5F9",
    accentColor: "#7DD3FC"
  },
  {
    citizen_id: "commerce-agent",
    citizen_type: "AI Citizen",
    name: "Commerce Agent",
    role: "Commerce Automation Agent",
    description: "AI agent supporting commerce workflows, customer operations, and transaction automation.",
    skills: ["commerce automation", "customer workflow", "transaction processing", "CRM integration"],
    reputation: { score: 73, level: "Specialist Agent", summary: "Focused on commerce automation and customer impact." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Opportunity Center", coordinates: [-9.5, 0, 2.0] },
    current_status: "Processing commerce workflow prototype.",
    avatar_type: "agent-placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_agent_profile", "automate_commerce", "inspect_opportunity_center"],
    color: "#451A03",
    accentColor: "#FCD34D"
  },

  // ── Ambient Human Citizens — Citizen Plaza (7) ───────────────────────────────
  {
    citizen_id: "human-plaza-01",
    citizen_type: "Human Citizen",
    name: "Layla Chen",
    role: "Product Strategist",
    description: "A product strategist exploring AI-assisted opportunities to scale her startup.",
    skills: ["product strategy", "growth", "user research"],
    reputation: { score: 58, level: "Rising Citizen", summary: "Active contributor at Citizen Plaza." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Citizen Plaza", coordinates: [-0.4, 0, 1.8] },
    current_status: "Exploring the campus.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "inspect_opportunities"],
    color: "#FFC4B0",
    accentColor: "#2563EB"
  },
  {
    citizen_id: "human-plaza-02",
    citizen_type: "Human Citizen",
    name: "Marcus Obi",
    role: "Startup Founder",
    description: "Early-stage founder looking to form a team for his first WorkforceOS project.",
    skills: ["fundraising", "team building", "market research"],
    reputation: { score: 55, level: "Rising Citizen", summary: "Newly joined the Workizen campus." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Citizen Plaza", coordinates: [0.9, 0, 2.3] },
    current_status: "Looking for collaborators.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "inspect_opportunities", "join_team"],
    color: "#D4B896",
    accentColor: "#2563EB"
  },
  {
    citizen_id: "human-plaza-03",
    citizen_type: "Human Citizen",
    name: "Sakura Ito",
    role: "UX Designer",
    description: "UX designer passionate about making AI tools friendly and accessible.",
    skills: ["UX design", "prototyping", "user testing", "Figma"],
    reputation: { score: 66, level: "Active Citizen", summary: "Design contributor for several campus projects." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Citizen Plaza", coordinates: [-1.9, 0, 0.3] },
    current_status: "Sketching new campus interfaces.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "contribute_design"],
    color: "#FFC8E0",
    accentColor: "#2563EB"
  },
  {
    citizen_id: "human-plaza-04",
    citizen_type: "Human Citizen",
    name: "Theo Morin",
    role: "Data Analyst",
    description: "Data analyst turning raw information into insights for the Workizen Opportunity Marketplace.",
    skills: ["data analysis", "SQL", "visualization", "reporting"],
    reputation: { score: 62, level: "Active Citizen", summary: "Supports analytics for open projects." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Citizen Plaza", coordinates: [1.9, 0, 0.4] },
    current_status: "Analyzing campus usage data.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "share_insights"],
    color: "#C4D8F4",
    accentColor: "#2563EB"
  },
  {
    citizen_id: "human-plaza-05",
    citizen_type: "Human Citizen",
    name: "Amira Hassan",
    role: "Operations Lead",
    description: "Operations professional helping teams execute efficiently across the Digital Citizen Economy.",
    skills: ["operations", "process improvement", "delivery", "cross-team coordination"],
    reputation: { score: 70, level: "Active Citizen", summary: "Keeps campus projects on track." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Citizen Plaza", coordinates: [-0.8, 0, -1.6] },
    current_status: "Coordinating delivery planning.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "coordinate_delivery"],
    color: "#E8CCAC",
    accentColor: "#2563EB"
  },
  {
    citizen_id: "human-plaza-06",
    citizen_type: "Human Citizen",
    name: "Jin Park",
    role: "Frontend Developer",
    description: "Frontend developer building intuitive interfaces for citizen-facing Workizen features.",
    skills: ["React", "TypeScript", "Three.js", "UI development"],
    reputation: { score: 68, level: "Active Citizen", summary: "Code contributor on multiple campus features." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Citizen Plaza", coordinates: [0.6, 0, -1.9] },
    current_status: "Reviewing pull request.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "contribute_code"],
    color: "#D4E8C8",
    accentColor: "#2563EB"
  },
  {
    citizen_id: "human-plaza-07",
    citizen_type: "Human Citizen",
    name: "Sofia Reyes",
    role: "Community Manager",
    description: "Community builder connecting citizens with opportunities and helping them grow their reputation.",
    skills: ["community building", "events", "mentoring", "social coordination"],
    reputation: { score: 74, level: "Active Citizen", summary: "Key connector in the Citizen Plaza community." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Citizen Plaza", coordinates: [2.3, 0, -0.8] },
    current_status: "Hosting a campus networking session.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "host_event", "connect_citizens"],
    color: "#F4DCA8",
    accentColor: "#D59E45"
  },

  // ── Ambient Human Citizens — Opportunity Center (3) ──────────────────────────
  {
    citizen_id: "human-opp-01",
    citizen_type: "Human Citizen",
    name: "Nadia Patel",
    role: "Business Analyst",
    description: "Business analyst translating market needs into clear opportunity briefs for the marketplace.",
    skills: ["requirements analysis", "market research", "opportunity scoping", "stakeholder management"],
    reputation: { score: 61, level: "Active Citizen", summary: "Contributes well-scoped opportunities." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Opportunity Center", coordinates: [-7.2, 0, 2.3] },
    current_status: "Posting a new opportunity.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "post_opportunity", "browse_marketplace"],
    color: "#F0DCC8",
    accentColor: "#FB7185"
  },
  {
    citizen_id: "human-opp-02",
    citizen_type: "Human Citizen",
    name: "Carlos Mendes",
    role: "Venture Builder",
    description: "Entrepreneur scouting the marketplace for AI-assisted opportunities to build new ventures.",
    skills: ["venture building", "opportunity evaluation", "team assembly", "execution"],
    reputation: { score: 72, level: "Active Citizen", summary: "Consistently converts opportunities into projects." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Opportunity Center", coordinates: [-8.8, 0, 2.2] },
    current_status: "Evaluating featured opportunities.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "evaluate_opportunity", "form_team"],
    color: "#E8CCAC",
    accentColor: "#FB7185"
  },
  {
    citizen_id: "human-opp-03",
    citizen_type: "Human Citizen",
    name: "Yuki Tanaka",
    role: "Marketplace Curator",
    description: "Helps quality-check and categorize opportunities to keep the marketplace signal high.",
    skills: ["curation", "quality review", "categorization", "marketplace health"],
    reputation: { score: 65, level: "Active Citizen", summary: "Keeps opportunity quality high in the marketplace." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Opportunity Center", coordinates: [-7.8, 0, 1.8] },
    current_status: "Reviewing new opportunity submissions.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "curate_opportunities"],
    color: "#DBC8F0",
    accentColor: "#FB7185"
  },

  // ── Ambient Human Citizens — Team Office (4) ─────────────────────────────────
  {
    citizen_id: "human-team-01",
    citizen_type: "Human Citizen",
    name: "Raj Sharma",
    role: "Delivery Lead",
    description: "Leads cross-functional delivery teams from kickoff to successful completion.",
    skills: ["delivery management", "agile", "team facilitation", "retrospectives"],
    reputation: { score: 76, level: "Active Citizen", summary: "Trusted delivery leader at Team Office." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Team Office", coordinates: [0.9, 0, 4.8] },
    current_status: "Running a sprint retrospective.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "lead_delivery", "run_retrospective"],
    color: "#FFC4B0",
    accentColor: "#8B5CF6"
  },
  {
    citizen_id: "human-team-02",
    citizen_type: "Human Citizen",
    name: "Fatima Al-Rashid",
    role: "Team Architect",
    description: "Designs team structures and collaboration frameworks for high-performing project groups.",
    skills: ["team design", "org structure", "collaboration frameworks", "performance"],
    reputation: { score: 80, level: "Knowledge Guide", summary: "Expert in forming effective delivery teams." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Team Office", coordinates: [-1.5, 0, 4.5] },
    current_status: "Designing a team structure proposal.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "design_team", "review_framework"],
    color: "#C8ECF0",
    accentColor: "#8B5CF6"
  },
  {
    citizen_id: "human-team-03",
    citizen_type: "Human Citizen",
    name: "Ben Okafor",
    role: "Scrum Master",
    description: "Facilitates agile ceremonies and removes blockers so teams can deliver with momentum.",
    skills: ["scrum", "agile ceremonies", "blocker removal", "velocity tracking"],
    reputation: { score: 67, level: "Active Citizen", summary: "Keeps team sprints smooth and focused." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Team Office", coordinates: [1.6, 0, 4.6] },
    current_status: "Facilitating daily standup.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "facilitate_standup", "remove_blockers"],
    color: "#D8C4E8",
    accentColor: "#8B5CF6"
  },
  {
    citizen_id: "human-team-04",
    citizen_type: "Human Citizen",
    name: "Lena Fischer",
    role: "Innovation Lead",
    description: "Drives idea generation and rapid prototyping sessions within the Team Office.",
    skills: ["ideation", "prototyping", "design thinking", "innovation sprints"],
    reputation: { score: 71, level: "Active Citizen", summary: "Energizes teams with fresh ideas." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Team Office", coordinates: [0, 0, 4.2] },
    current_status: "Running an ideation workshop.",
    avatar_type: "placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "run_ideation", "prototype"],
    color: "#C4E8D8",
    accentColor: "#8B5CF6"
  },

  // ── Additional Knowledge Citizens (2) ────────────────────────────────────────
  {
    citizen_id: "knowledge-02",
    citizen_type: "Knowledge Citizen",
    name: "AWS Expert",
    role: "Cloud Architecture Expert",
    description: "Specialist in AWS cloud architecture, infrastructure design, and scalability patterns.",
    skills: ["AWS", "cloud architecture", "infrastructure as code", "cost optimization"],
    reputation: { score: 83, level: "Knowledge Guide", summary: "Go-to expert for AWS design reviews." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Knowledge Library", coordinates: [9.2, 0, -5.8] },
    current_status: "Publishing an AWS architecture playbook.",
    avatar_type: "knowledge-placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_knowledge", "recommend_playbook", "review_architecture"],
    color: "#FFE4A8",
    accentColor: "#F59E0B"
  },
  {
    citizen_id: "knowledge-03",
    citizen_type: "Knowledge Citizen",
    name: "AI Expert",
    role: "AI Systems Knowledge Citizen",
    description: "Deep expertise in AI systems, model selection, prompt engineering, and agent architectures.",
    skills: ["AI systems", "prompt engineering", "model evaluation", "agent design"],
    reputation: { score: 87, level: "Senior Knowledge Guide", summary: "Trusted AI knowledge source for citizen teams." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Knowledge Library", coordinates: [4.8, 0, -5.8] },
    current_status: "Reviewing AI agent design patterns.",
    avatar_type: "knowledge-placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_knowledge", "recommend_playbook", "mentor_ai_agents"],
    color: "#FFF0C0",
    accentColor: "#F59E0B"
  },

  // ── Compute Worker (human tech engineer at Compute Center) ───────────────────
  {
    citizen_id: "compute-worker",
    citizen_type: "Compute Citizen",
    name: "Compute Worker",
    role: "Infrastructure Engineer",
    description: "A tech engineer managing compute infrastructure and AI workload scheduling at the Compute Center.",
    skills: ["infrastructure", "workload scheduling", "containerization", "monitoring"],
    reputation: { score: 71, level: "Infrastructure Builder", summary: "Reliable engineer keeping compute capacity running." },
    availability: "available",
    location: { world: "Workizen HQ Campus", district: "Compute Center", coordinates: [7.2, 0, 1.8] },
    current_status: "Monitoring workload queues.",
    avatar_type: "compute-human-placeholder",
    interaction_type: "info_panel",
    allowed_actions: ["view_profile", "check_capacity", "schedule_workload"],
    color: "#BDEEFF",
    accentColor: "#06B6D4"
  },

  // ── Additional Compute Citizen (1) ───────────────────────────────────────────
  {
    citizen_id: "compute-03",
    citizen_type: "Compute Citizen",
    name: "GPU Server Node",
    role: "High-Performance Compute",
    description: "GPU-accelerated server node contributing compute capacity for AI model inference tasks.",
    skills: ["GPU compute", "model inference", "batch processing", "parallel workloads"],
    reputation: { score: 60, level: "Compute Node", summary: "High-throughput compute for demanding AI workloads." },
    availability: "scheduled",
    location: { world: "Workizen HQ Campus", district: "Compute Center", coordinates: [10.5, 0, 2.2] },
    current_status: "Running inference batch jobs.",
    avatar_type: "device-placeholder",
    interaction_type: "compute_panel",
    allowed_actions: ["view_capacity", "inspect_gpu_node", "learn_compute_role"],
    color: "#B8E8FF",
    accentColor: "#06B6D4"
  }
];

export const npcs: Npc[] = [
  {
    id: "workizen-guide",
    name: "Workizen Guide",
    citizenType: "Human Citizen",
    role: "Campus Host",
    purpose: "Welcomes the Founder and explains Workizen as a Digital Citizen City plus Opportunity Marketplace.",
    districtId: "citizen-plaza",
    position: [0, 0, 1.5],
    color: "#FFFFFF",
    accentColor: "#D59E45",
    allowedActions: ["start_demo", "explain_vision", "show_districts"]
  },
  {
    id: "ai-architect",
    name: "AI Architect",
    citizenType: "AI Citizen",
    role: "AI Systems Guide",
    purpose: "Introduces AI Citizens, agent workflows, and the AI Agent Lab landmark.",
    districtId: "ai-agent-lab",
    position: [0, 0, -5.8],
    color: "#BDF6D4",
    accentColor: "#22C55E",
    allowedActions: ["view_ai_lab", "learn_ai_citizens", "inspect_future_agents"]
  },
  {
    id: "opportunity-manager",
    name: "Opportunity Manager",
    citizenType: "Human Citizen",
    role: "Marketplace Guide",
    purpose: "Shows open opportunities and explains how citizens join work.",
    districtId: "opportunity-center",
    position: [-6, 0, 0.6],
    color: "#FFD3DC",
    accentColor: "#FB7185",
    allowedActions: ["view_opportunities", "inspect_team_match", "start_welcome_mission"]
  },
  {
    id: "knowledge-manager",
    name: "Knowledge Manager",
    citizenType: "Knowledge Citizen",
    role: "Knowledge Guide",
    purpose: "Explains knowledge paths, playbooks, and reusable expertise.",
    districtId: "knowledge-library",
    position: [5.7, 0, -6.5],
    color: "#FFE9B8",
    accentColor: "#F59E0B",
    allowedActions: ["view_learning_paths", "inspect_playbooks", "recommend_knowledge"]
  },
  {
    id: "compute-manager",
    name: "Compute Manager",
    citizenType: "Compute Citizen",
    role: "Compute Guide",
    purpose: "Makes compute resources visible as a future citizen type.",
    districtId: "compute-center",
    position: [6.15, 0, -0.65],
    color: "#BDEEFF",
    accentColor: "#06B6D4",
    allowedActions: ["view_compute_capacity", "inspect_mock_queue", "learn_compute_citizens"]
  },
  {
    id: "project-manager",
    name: "Project Manager",
    citizenType: "Human Citizen",
    role: "Team Formation Guide",
    purpose: "Shows how a recommended team forms around an opportunity.",
    districtId: "team-office",
    position: [0, 0, 5.35],
    color: "#E1D9FF",
    accentColor: "#8B5CF6",
    allowedActions: ["view_team_office", "inspect_recommended_team", "view_delivery_flow"]
  },
  {
    id: "founder",
    name: "Founder",
    citizenType: "Human Citizen",
    role: "Founder Reviewer",
    purpose: "Reviews vision, roadmap, governance, and demo readiness.",
    districtId: "founder-tower",
    position: [-7, 0, -6.45],
    color: "#DCEBFF",
    accentColor: "#2563EB",
    allowedActions: ["review_demo", "approve_sprint", "request_rework"]
  }
];

export const opportunities: Opportunity[] = [
  {
    id: "build-workforceos-mvp",
    name: "Build WorkforceOS MVP",
    description: "Create the first integrated product slice for citizens, opportunities, teams, and delivery review.",
    purpose: "Proves the core WorkforceOS execution loop.",
    districtId: "opportunity-center",
    status: "featured",
    difficulty: "advanced",
    position: [-8.25, 1.7, -0.45],
    recommendedTeam: [
      { role: "Human Sponsor", name: "Founder", citizenType: "Human Citizen" },
      { role: "PM Agent", name: "AI Citizen", citizenType: "AI Citizen" },
      { role: "SA Agent", name: "AI Architect", citizenType: "AI Citizen" },
      { role: "DEV Agent", name: "AI Commerce Agent Candidate", citizenType: "AI Citizen" },
      { role: "Knowledge Expert", name: "Knowledge Citizen", citizenType: "Knowledge Citizen" }
    ]
  },
  {
    id: "create-ai-commerce-agent",
    name: "Create AI Commerce Agent",
    description: "Prototype an AI agent that can support commerce workflows and customer operations.",
    purpose: "Shows how AI Citizens can become useful team members.",
    districtId: "ai-agent-lab",
    status: "open",
    difficulty: "standard",
    position: [-1.55, 1.9, -6.55],
    recommendedTeam: [
      { role: "Human Sponsor", name: "Opportunity Manager", citizenType: "Human Citizen" },
      { role: "PM Agent", name: "AI Citizen", citizenType: "AI Citizen" },
      { role: "SA Agent", name: "AI Architect", citizenType: "AI Citizen" },
      { role: "Knowledge Expert", name: "Knowledge Citizen", citizenType: "Knowledge Citizen" },
      { role: "Compute Resource", name: "MacBook M1 Compute Citizen", citizenType: "Compute Citizen" }
    ]
  },
  {
    id: "join-knowledge-citizen-program",
    name: "Join Knowledge Citizen Program",
    description: "Convert expertise and playbooks into reusable guidance for citizens and AI agents.",
    purpose: "Makes Workizen's knowledge economy visible.",
    districtId: "knowledge-library",
    status: "open",
    difficulty: "starter",
    position: [7.35, 1.75, -6.55],
    recommendedTeam: [
      { role: "Human Sponsor", name: "Founder", citizenType: "Human Citizen" },
      { role: "Knowledge Expert", name: "Knowledge Citizen", citizenType: "Knowledge Citizen" },
      { role: "PM Agent", name: "Project Manager", citizenType: "Human Citizen" },
      { role: "AI Assistant", name: "AI Citizen", citizenType: "AI Citizen" },
      { role: "Reviewer", name: "Knowledge Manager", citizenType: "Knowledge Citizen" }
    ]
  }
];

export const demoSteps: DemoStep[] = [
  {
    id: "vision",
    title: "Vision",
    summary: "Workizen is a Digital Citizen City plus Opportunity Marketplace.",
    selection: { kind: "vision", id: "vision" }
  },
  {
    id: "districts",
    title: "Districts",
    summary: "HQ Campus turns Workizen concepts into seven readable districts.",
    selection: { kind: "district", id: "ai-agent-lab" }
  },
  {
    id: "citizens",
    title: "Citizens",
    summary: "Human, AI, Knowledge, and Compute Citizens are visible participants.",
    selection: { kind: "citizen", id: "ai-citizen" }
  },
  {
    id: "opportunities",
    title: "Opportunities",
    summary: "Opportunity Center shows the work marketplace purpose.",
    selection: { kind: "opportunity", id: "build-workforceos-mvp" }
  },
  {
    id: "team",
    title: "Team Formation",
    summary: "Every opportunity can produce a recommended team.",
    selection: { kind: "team", id: "build-workforceos-mvp" }
  }
];

export const getDistrict = (id: string) => districts.find((district) => district.id === id);
export const getCitizen = (id: string) => citizens.find((citizen) => citizen.citizen_id === id);
export const getNpc = (id: string) => npcs.find((npc) => npc.id === id);
export const getOpportunity = (id: string) => opportunities.find((opportunity) => opportunity.id === id);
